[build]
  publish = "dist/uploadWAV"
  command = "ng build --prod"
  functions = "./functions"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
# Production context: all deploys from the Production branch set in your site’s
# Branches settings in the UI will inherit these settings.
[context.production]
